# Git URL : https://github.com/realm/SwiftLint
# Reference : https://realm.github.io/SwiftLint/index.html
excluded:
  - Pods
  - Macro/App/AppDelegate.swift
  - Macro/App/SceneDelegate.swift
analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
# 추가한 rules
  - todo
  - orphaned_doc_comment
  - empty_xctest_method
  - redundant_type_annotation
  - number_separator
  - empty_count
  - object_literal
  - file_name
  - trailing_whitespace
  - sorted_imports
  - file_header
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - statement_position

# Customized Configurable Rules
line_length: 250
force_cast: error


