#
# 개발 및 테스트를 위한 도커 컴포즈입니다.
# 실제 배포에선 사용되지 않습니다.
#
version: "1"
services:
  node:
    image: "node:20.5.1"
    user: "root"
    working_dir: "/node"
    volumes:
      - ./:/node
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - MYSQL_USER=macro
      - MYSQL_PASSWORD=macro
      - MYSQL_DATABASE=macro_dev_db
    command: sh -c "npm install && npm run start:debug" 
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.2.0
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=macro
      - MYSQL_USER=macro
      - MYSQL_PASSWORD=macro
      - MYSQL_DATABASE=macro_dev_db
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "macro", "-pmacro", "-e", "SELECT 1"]
      interval: 1s
      timeout: 30s
      retries: 15
      start_period: 10s

  redis:
    container_name: redis
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/var/lib/redis
    labels:
      - com.host.description=label

volumes:
  mysql-db-data:
  redis-volume: