version: '1'
services:
  node:
    environment:
      - NODE_ENV=development
      - MYSQL_USER=macro
      - MYSQL_PASSWORD=macro
      - MYSQL_DATABASE=macro_dev_db
    command: sh -c "npm install && npm run start:debug" 
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:8.2.0
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=macro
      - MYSQL_USER=macro
      - MYSQL_PASSWORD=macro
      - MYSQL_DATABASE=macro_dev_db
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "macro", "-pmacro", "-e", "SELECT 1"]
      interval: 1s
      timeout: 30s
      retries: 15
      start_period: 10s
volumes:
  mysql-db-data: