version: "1"
services:
  node:
    image: "node:20.5.1"
    user: "node"
    working_dir: "/node"
    environment:
      - NODE_ENV=development
      - MYSQL_USER=macro
      - MYSQL_PASSWORD=macro
      - MYSQL_DATABASE=macro_dev_db
    volumes:
      - ./:/node
    command: sh -c "npm install -D  && npm run start:debug" 
    ports:
      - 3000:3000
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=macro
      - MYSQL_USER=macro
      - MYSQL_PASSWORD=macro
      - MYSQL_DATABASE=macro_dev_db
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-db-data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "macro", "-pmacro", "-e", "SELECT 1"]
      interval: 1s
      timeout: 30s
      retries: 15
      start_period: 10s
volumes:
  mysql-db-data:
