name: deploy Project to Server

on:
  push:
    branches: [ "feature/deploy" ]

env:
  CONTAINER_IMAGE_TAG_NAME: backend

jobs:
  build_and_push:
    name: Build nest.js and docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'feature/deploy'

      - name: Setting application.yaml before building app
        env:
          APPLICATION_YAML_BASE64: ${{ secrets.APPLICATION_YAML_BASE64 }}
        run: |
          echo $APPLICATION_YAML_BASE64 | base64 --decode > ./server/application.yaml

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.NCLOUD_CONTAINER_REGISTRY_ENDPOINT }}
          username: ${{ secrets.NCLOUD_ACCESS_KEY }}
          password: ${{ secrets.NCLOUD_SECRET_KEY }}
          
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image and push to registry
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.NCLOUD_CONTAINER_REGISTRY_ENDPOINT }}/${{ env.CONTAINER_IMAGE_TAG_NAME }}:latest
            ${{ secrets.NCLOUD_CONTAINER_REGISTRY_ENDPOINT }}/${{ env.CONTAINER_IMAGE_TAG_NAME }}:${{ github.run_number }}
          context: ./server
          

  
  
  pull_and_run:
    name: Connect to instance and pull image from registry and run application
    needs: build_and_push
    runs-on: ubuntu-latest

    steps:
      - name: connect ssh and running
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCLOUD_SERVER_INSTANCE_HOST }}
          port: ${{ secrets.NCLOUD_SERVER_INSTANCE_PORT }}
          username: root
          key: ${{ secrets.NCLOUD_SERVER_INSTANCE_PRIVATE_KEY }}
          passphrase: ${{ secrets.NCLOUD_SERVER_INSTANCE_PRIVATE_KEY_PASSPHRASE }}
          script: |
            docker login ${{ secrets.NCLOUD_CONTAINER_REGISTRY_ENDPOINT }} -u ${{ secrets.NCLOUD_ACCESS_KEY }} -p ${{ secrets.NCLOUD_SECRET_KEY }}
            docker pull ${{ secrets.NCLOUD_CONTAINER_REGISTRY_ENDPOINT }}/${{ env.CONTAINER_IMAGE_TAG_NAME }}
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docekr run -d -p ${{ secrets.APPLICATION_PORT }}:3000 ${{ secrets.NCLOUD_CONTAINER_REGISTRY_ENDPOINT }}/${{ env.CONTAINER_IMAGE_TAG_NAME }}:latest
            docker image prune -f
